### ISSUE TITLE
oshamashama 以外が見つけたゴママヨを記録してもよいのか

### ISSUE THREAD

**Issue by private-yusuke** [open-gomamayo/gomamayo#3]
# 概要

このリポジトリ https://github.com/oshamashama/gomamayo の About には、以下のような記載がある。

> oshamashama が見つけたゴママヨを記録します

しかしながら、常日頃からゴママヨを探し求めている我々としては、ゴママヨを contribute したいという欲求がある。

@oshamashama
- このリポジトリには、oshamashama 以外が発見したゴママヨを掲載してもよいのでしょうか？
  - related: #1, #2
- また、oshamashama 以外によって、すでにインターネット等においてその存在が明言されたゴママヨをこのリポジトリで掲載することは許容されるのでしょうか？

**Comment by private-yusuke** [comment]
Pull Request によって提案されたゴママヨは @oshamashama が確認することになると思うので、形式上は @oshamashama 「も」発見したと主張することはできる気がします。しかし、一番最初に発見されたオリジナリティのあるゴママヨのみを掲載したいという方向性を担保したいのであれば、「oshamashama を筆頭に皆さんが発見したゴママヨを記録します」のような書き換えをするのが良さそうです。

**Comment by Okabe-Junya** [comment]
厳密性を主張していてえらい

**Comment by oshamashama** [comment]
### > このリポジトリには、oshamashama 以外が発見したゴママヨを掲載してもよいのでしょうか？ 

たくさんの人によって ゴママヨ が追加され、ゴママヨ が増えるのは喜ばしいことですので oshamashama による発見に限らないことにします。

そのため、
> oshamashama が見つけたゴママヨを記録します

を修正し
> ゴママヨを蓄積します

とします。


### > また、oshamashama 以外によって、すでにインターネット等においてその存在が明言されたゴママヨをこのリポジトリで掲載することは許容されるのでしょうか？

厳密にゴママヨであることへの言及が初出であることを担保することは困難であるため、初出に限らないことにします。
ただし、リポジトリ内に重複する記録は必要ないため、リポジトリ内で初出であることを条件にします。

**Comment by private-yusuke** [comment]
返信ありがとうございます。良さそうです。リポジトリの description が変更されていることを確認したため close します。
