### ISSUE TITLE
「oshamashama が見つけたゴママヨ」は初出であることを含意するのか

### ISSUE THREAD

**Issue by cyanolupus** [open-gomamayo/gomamayo#4]
# 概要

このリポジトリの description には 「oshamashama が見つけたゴママヨ」と記されていますが、これは初出である必要はありますか？

例えば、https://github.com/oshamashama/gomamayo/commit/5cbab9981077da79ebc4bbdbb7c6d53e19fd61d0 で追加された「ヘアアイロン」はコミット時点で既出となっています（少なくとも 2020/10/14 には https://x.com/DOCTYPE_utml/status/1316167155822415873 ）

初出に限定しない場合、先人に敬意を表してクレジット表記をするのはどうでしょうか

**Comment by cyanolupus** [comment]
関連する commit
- https://github.com/oshamashama/gomamayo/commit/5cbab9981077da79ebc4bbdbb7c6d53e19fd61d0 https://x.com/DOCTYPE_utml/status/1316167155822415873
- https://github.com/oshamashama/gomamayo/commit/9e48bbc18494e97510fba0c6be8c637d2723ab79 https://x.com/lemon_beads/status/1244635065054683136

関連する PR
- https://github.com/oshamashama/gomamayo/pull/1 https://x.com/ThinaticSystem/status/1329309735879806981

**Comment by cyanolupus** [comment]
https://github.com/oshamashama/gomamayo/issues/3#issuecomment-2155857977

**Comment by oshamashama** [comment]
ありがとうございます。これへの回答は上記の通りおおむね、https://github.com/oshamashama/gomamayo/issues/3#issuecomment-2155857977 で満たさると考えています。

1つ補足として
> 初出に限定しない場合、先人に敬意を表してクレジット表記をするのはどうでしょうか

については、先人が複数いた場合にいくつ掲載するかという問題や、
最初のみを掲載するとしてそれが初出であることを保証できないためやらない方針で行きます。

ただし、このリポジトリにおけるゴママヨが初出であることを保証するわけではないことをどこかに明記することを検討させていただきます。
