### ISSUE TITLE
Organization への移行

### ISSUE THREAD

**Issue by cyanolupus** [open-gomamayo/gomamayo#7]
# 概要

https://github.com/oshamashama/gomamayo/issues/3#issuecomment-2155857977 で示された通り、このリポジトリは一般のゴママヨを蓄積するものになると思われます。そこでオーナーを個人から Organization に移行してはいかがでしょうか。

開かれたゴママヨであることを意識させたいです。

**Comment by oshamashama** [comment]
良さそうです。

**Comment by oshamashama** [comment]
移行しました。

**Comment by Okabe-Junya** [comment]
おれもopen gomamayoに入れてもらってもいいですか？
