### ISSUE TITLE
[Member Ship Request] Open-Gomamayo に入りたいです

### ISSUE THREAD

**Issue by Okabe-Junya** [open-gomamayo/gomamayo#8]
## Request

#7 でオーガナイゼーション化をしましたが、おれもGomamayoに気持ちがあるので入れて欲しいです。

**Comment by Okabe-Junya** [comment]
（過去に Issue / PR を作成した人も cc させて下さい）

cc @private-yusuke @cyanolupus @HosokawaR

**Comment by oshamashama** [comment]
Invited

**Comment by Okabe-Junya** [comment]
Thanks!
